id: A9C4F2873
title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of the
  Guru (Lama Sangdü)'
type: translation
pechas:
- IB4CE0E6A
- IABD4810E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:58:14.467713
  last_modified_at: 2023-01-04 11:58:14.467726
  collections:
  - Guru Chökyi Wangchuk
  - Works of Tibetan Masters
alignment_to_base:
  IB4CE0E6A/1442: 52C4
  IABD4810E/B8B3: 52C4
